name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactoryssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Xserver
        run: |
          rsync -avz --delete --exclude '.git/' --exclude '.github/' ./ lidgee@sv10347.xserver.jp:/home/lidgee/koinu-step.com/public_html/ --quiet
